// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9nEStIaV5-SqZVx6845yhcGvnL7A800',
    appId: '1:707195161078:web:a47bad1592ba069def1fd7',
    messagingSenderId: '707195161078',
    projectId: 'ecommerceapp-6c4ad',
    authDomain: 'ecommerceapp-6c4ad.firebaseapp.com',
    storageBucket: 'ecommerceapp-6c4ad.appspot.com',
    measurementId: 'G-D69REBMLWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeY0BXAcQx1AO93LQwVRC9_rHqYBL9FQc',
    appId: '1:707195161078:android:1947898b1355e960ef1fd7',
    messagingSenderId: '707195161078',
    projectId: 'ecommerceapp-6c4ad',
    storageBucket: 'ecommerceapp-6c4ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJr6hokXRpWL2UpM7QgFJAlH4-qi2LG4',
    appId: '1:707195161078:ios:9dcf49a7d55bbdc3ef1fd7',
    messagingSenderId: '707195161078',
    projectId: 'ecommerceapp-6c4ad',
    storageBucket: 'ecommerceapp-6c4ad.appspot.com',
    iosBundleId: 'com.example.ecomproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcJr6hokXRpWL2UpM7QgFJAlH4-qi2LG4',
    appId: '1:707195161078:ios:9dcf49a7d55bbdc3ef1fd7',
    messagingSenderId: '707195161078',
    projectId: 'ecommerceapp-6c4ad',
    storageBucket: 'ecommerceapp-6c4ad.appspot.com',
    iosBundleId: 'com.example.ecomproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa9nEStIaV5-SqZVx6845yhcGvnL7A800',
    appId: '1:707195161078:web:3f4390017b9a7167ef1fd7',
    messagingSenderId: '707195161078',
    projectId: 'ecommerceapp-6c4ad',
    authDomain: 'ecommerceapp-6c4ad.firebaseapp.com',
    storageBucket: 'ecommerceapp-6c4ad.appspot.com',
    measurementId: 'G-JCBMVC8QYN',
  );
}
